# Generated by Django 4.0.1 on 2022-06-24 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 9, 15, 59, 448132)),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='measurement.sensor'),
        ),
    ]
