# Generated by Django 4.0.1 on 2022-06-24 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_data_alter_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 15, 56, 68498)),
        ),
    ]
