# Generated by Django 4.0.1 on 2022-06-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_rename_sensor_id_measurement_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='data',
            new_name='date',
        ),
    ]
