# Generated by Django 4.0.1 on 2022-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_rename_data_measurement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
